nohup: ignoring input
Traceback (most recent call last):
  File "/scratch0/liuguan5/nips24selfcorrection/prompting.py", line 176, in <module>
    tokenizer, llm = init_model(args)
  File "/scratch0/liuguan5/nips24selfcorrection/prompting.py", line 29, in init_model
    tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-v0.1", cache_dir="/data/bochuan/DPO/cache")
  File "/scratch0/liuguan5/miniconda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/scratch0/liuguan5/miniconda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/scratch0/liuguan5/miniconda/lib/python3.10/site-packages/transformers/utils/hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "/scratch0/liuguan5/miniconda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/scratch0/liuguan5/miniconda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1224, in hf_hub_download
    os.makedirs(storage_folder, exist_ok=True)
  File "/scratch0/liuguan5/miniconda/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/scratch0/liuguan5/miniconda/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/scratch0/liuguan5/miniconda/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/scratch0/liuguan5/miniconda/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'
